import { Injectable } from '@nestjs/common';
import { GithubService } from '../github/github.service';
import { TemplateService } from '../templates/template.service';
import { CreateComponentDto } from './dto/create-component.dto';

@Injectable()
export class ComponentsService {
  constructor(
    private readonly githubService: GithubService,
    private readonly templateService: TemplateService,
  ) {}

  async createComponent(dto: CreateComponentDto) {
    try {
      // 1. Generate all component files from templates
      const files = this.templateService.generateComponentFiles(dto);

      // 2. Create a branch and PR via GitHub API
      const branchName = `community/add-${dto.name}`;
      const prTitle = `feat(community): add ${dto.name} component`;
      const prBody = this.buildPrBody(dto);

      const prUrl = await this.githubService.createPullRequest({
        branchName,
        title: prTitle,
        body: prBody,
        files,
        author: dto.author,
      });

      return {
        success: true,
        prUrl,
        message: `Pull request created successfully for ${dto.name}`,
      };
    } catch (error) {
      return {
        success: false,
        message: `Failed to create component: ${error.message}`,
        errors: [error.message],
      };
    }
  }

  async validate(dto: Partial<CreateComponentDto>) {
    const errors: string[] = [];

    if (dto.name && !/^[a-z][a-z0-9-]*$/.test(dto.name)) {
      errors.push('Name must be lowercase kebab-case');
    }

    if (dto.selector && !/^[a-z]+-[a-z0-9-]+$/.test(dto.selector)) {
      errors.push('Selector must follow pattern: prefix-name');
    }

    if (dto.description && dto.description.length < 20) {
      errors.push('Description must be at least 20 characters');
    }

    if (dto.code?.typescript && !dto.code.typescript.includes('@Component')) {
      errors.push('TypeScript must contain an @Component decorator');
    }

    return { valid: errors.length === 0, errors };
  }

  async checkNameAvailability(name: string) {
    const exists = await this.githubService.fileExists(
      `libs/community/src/lib/${name}`
    );
    return { available: !exists };
  }

  private buildPrBody(dto: CreateComponentDto): string {
    return `## New Community Component: \`${dto.selector}\`

### Description
${dto.description}

### Category
${dto.category}

### Author
- **Name:** ${dto.author.name}
- **GitHub:** @${dto.author.github}

### Component API

#### Inputs
${dto.inputs.map(i => `| \`${i.name}\` | \`${i.type}\` | \`${i.defaultValue || '-'}\` | ${i.description} |`).join('\n')}

#### Outputs
${dto.outputs.map(o => `| \`${o.name}\` | \`${o.type}\` | ${o.description} |`).join('\n')}

### Checklist
- [x] Component code included
- [x] Storybook story generated
- [ ] Unit tests (auto-generated shell)
- [ ] Accessibility reviewed
- [ ] Documentation complete

---
*This PR was auto-generated by the Design System Portal.*`;
  }
}
